//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipCardGame.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlipCardGameEntities : DbContext
    {
        public FlipCardGameEntities()
            : base("name=FlipCardGameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactUs> ContactUs { get; set; }
        public virtual DbSet<GameQuestions> GameQuestions { get; set; }
        public virtual DbSet<Games> Games { get; set; }
        public virtual DbSet<SitePageFragments> SitePageFragments { get; set; }
        public virtual DbSet<SitePages> SitePages { get; set; }
        public virtual DbSet<UserPlayedGames> UserPlayedGames { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
