//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipCardGame.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameQuestions
    {
        public int GameID { get; set; }
        public int QuestionIndex { get; set; }
        public string QuestionContent { get; set; }
        public string AnswerContent { get; set; }
    
        public virtual Games Games { get; set; }
    }
}
