//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipCardGame.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUs
    {
        public long IDMessage { get; set; }
        public System.DateTime MessageDateTime { get; set; }
        public string PersonFullName { get; set; }
        public string Mobile { get; set; }
        public string EMail { get; set; }
        public string WebSite { get; set; }
        public string MessageSubject { get; set; }
        public string MessageBody { get; set; }
        public bool IsRead { get; set; }
    }
}
